<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6bhGtz\InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6bhGtz/InfrastructureApp_Infrastructure_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6bhGtz.legacy');

    return;
}

if (!\class_exists(InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV6bhGtz\InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, InfrastructureApp_Infrastructure_KernelDevDebugContainer::class, false);
}

return new \ContainerV6bhGtz\InfrastructureApp_Infrastructure_KernelDevDebugContainer([
    'container.build_hash' => 'V6bhGtz',
    'container.build_id' => 'a1f0e1f2',
    'container.build_time' => 1571992386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6bhGtz');
