register:
  path: '/users'
  methods: ['POST']
  defaults:
    _controller: 'App\User\Infrastructure\Controller\Action\RegisterAction'

fetch:
  path: '/users/{id}'
  methods: ['GET']
  defaults:
    _controller: 'App\User\Infrastructure\Controller\Action\GetAction'
  requirements:
    id: '\d+'

browse:
  path: '/users'
  methods: ['GET']
  defaults:
    _controller: 'App\User\Infrastructure\Controller\Action\BrowseAction'

remove:
  path: '/users/{id}'
  methods: ['DELETE']
  defaults:
    _controller: 'App\User\Infrastructure\Controller\Action\RemoveAction'
  requirements:
    id: '\d+'