parameters:
    locale: 'en'

imports:
    - { resource: "services/**/*.yaml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Predis\Client: '@snc_redis.default'

    App\User\Domain\Repository\Users: '@App\User\Infrastructure\Repository\UsersRedisRepository'
    App\Shared\Infrastructure\Service\Generator\IdGeneratorInterface: '@App\Shared\Infrastructure\Service\Generator\RandomIntegerIdGenerator'
    App\User\Infrastructure\Security\Hasher\PasswordHasherInterface: '@App\User\Infrastructure\Security\Hasher\BcryptPasswordHasher'
    App\User\Infrastructure\Service\Factory\UsersFactoryInterface: '@App\User\Infrastructure\Service\Factory\UsersFactory'

