parameters:
    locale: 'en'

imports:
    - { resource: "services/**/*.yaml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Predis\Client: '@snc_redis.default'

    # SHARED
    App\Shared\Infrastructure\Generator\IdGeneratorInterface: '@App\Shared\Infrastructure\Generator\RandomIntegerIdGenerator'
    App\Shared\Infrastructure\EventStore\EventStore: '@App\Shared\Infrastructure\EventStore\RedisEventStore'

    # USER
    App\User\Domain\Repository\Users: '@App\User\Infrastructure\Repository\UsersRedisRepository'
    App\User\Infrastructure\ReadModel\Repository\UserViews: '@App\User\Infrastructure\ReadModel\Repository\UserViewsRedisRepository'

    App\User\Infrastructure\Security\Hasher\PasswordHasherInterface: '@App\User\Infrastructure\Security\Hasher\BcryptPasswordHasher'

    App\User\Infrastructure\Factory\UsersFactoryInterface: '@App\User\Infrastructure\Factory\UsersFactory'
    App\User\Infrastructure\ReadModel\Factory\UserViewsFactoryInterface: '@App\User\Infrastructure\ReadModel\Factory\UserViewsFactory'

    App\Shared\Application\CommandBusInterface: '@App\User\Application\CommandBus\SimpleCommandBus'

    # ADMIN
    App\Admin\Domain\Repository\Admins: '@App\Admin\Infrastructure\Repository\EventSourcedAdminRepository'

    # @TODO make na interface!
    App\Shared\Infrastructure\Api\ResponseFactory:
        class: App\Shared\Infrastructure\Api\ResponseFactory


