<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Security\Hasher\Md5PasswordHasher' shared autowired service.

include_once $this->targetDirs[3].'/src/Infrastructure/Security/Hasher/PasswordHasherInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Security/Hasher/Md5PasswordHasher.php';

return $this->services['App\\Infrastructure\\Security\\Hasher\\Md5PasswordHasher'] = new \App\Infrastructure\Security\Hasher\Md5PasswordHasher();
