<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Controller\Action\RegisterAction' shared autowired service.

include_once $this->targetDirs[3].'/src/Infrastructure/Controller/Action/RegisterAction.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Service/Generator/IdGeneratorInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Service/Generator/RandomIntegerIdGenerator.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Security/Hasher/PasswordHasherInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Security/Hasher/BcryptPasswordHasher.php';

return $this->services['App\\Infrastructure\\Controller\\Action\\RegisterAction'] = new \App\Infrastructure\Controller\Action\RegisterAction(($this->services['App\\Infrastructure\\Repository\\UsersRedisRepository'] ?? $this->load('getUsersRedisRepositoryService.php')), ($this->services['App\\Infrastructure\\Service\\Generator\\RandomIntegerIdGenerator'] ?? ($this->services['App\\Infrastructure\\Service\\Generator\\RandomIntegerIdGenerator'] = new \App\Infrastructure\Service\Generator\RandomIntegerIdGenerator())), ($this->services['App\\Infrastructure\\Security\\Hasher\\BcryptPasswordHasher'] ?? ($this->services['App\\Infrastructure\\Security\\Hasher\\BcryptPasswordHasher'] = new \App\Infrastructure\Security\Hasher\BcryptPasswordHasher())));
