<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'snc_redis.command.flush_all' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/snc/redis-bundle/Command/RedisBaseCommand.php';
include_once $this->targetDirs[3].'/vendor/snc/redis-bundle/Command/RedisFlushallCommand.php';

$this->privates['snc_redis.command.flush_all'] = $instance = new \Snc\RedisBundle\Command\RedisFlushallCommand();

$instance->setClientLocator(($this->privates['.service_locator.YFkw8Ch'] ?? $this->load('get_ServiceLocator_YFkw8ChService.php')));
$instance->setName('redis:flushall');

return $instance;
