<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Repository\UsersRedisRepository' shared autowired service.

include_once $this->targetDirs[3].'/src/Application/Repository/UsersRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Repository/UsersRedisRepository.php';

return $this->services['App\\Infrastructure\\Repository\\UsersRedisRepository'] = new \App\Infrastructure\Repository\UsersRedisRepository(($this->privates['snc_redis.default'] ?? $this->load('getSncRedis_DefaultService.php')), ($this->services['App\\Infrastructure\\Service\\Factory\\UsersFactory'] ?? $this->load('getUsersFactoryService.php')));
