services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  hashers:
    namespace: App\Infrastructure\Security\Hasher\
    resource: "%kernel.project_dir%/src/Infrastructure/Security/Hasher/*"