<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YFkw8Ch' shared service.

return $this->privates['.service_locator.YFkw8Ch'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'snc_redis.default' => ['privates', 'snc_redis.default', 'getSncRedis_DefaultService.php', true],
], [
    'snc_redis.default' => '?',
]);
