<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Controller\Action\RegisterAction' shared autowired service.

include_once $this->targetDirs[3].'/src/Infrastructure/Controller/Action/RegisterAction.php';

return $this->services['App\\Infrastructure\\Controller\\Action\\RegisterAction'] = new \App\Infrastructure\Controller\Action\RegisterAction(($this->services['App\\Infrastructure\\Repository\\UsersRedisRepository'] ?? $this->load('getUsersRedisRepositoryService.php')), ($this->services['App\\Infrastructure\\Service\\Factory\\UsersFactory'] ?? $this->load('getUsersFactoryService.php')));
