<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Infrastructure\Repository\UsersInMemoryRepository' shared autowired service.

include_once $this->targetDirs[3].'/src/Application/Repository/UsersRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Infrastructure/Repository/UsersInMemoryRepository.php';

return $this->services['App\\Infrastructure\\Repository\\UsersInMemoryRepository'] = new \App\Infrastructure\Repository\UsersInMemoryRepository();
