services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  admin_repositories:
    namespace: App\Admin\Infrastructure\Repository\
    resource: "%kernel.project_dir%/src/Admin/Infrastructure/Repository/*"