services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  user_actions:
    namespace: App\User\Infrastructure\Controller\Action\
    resource: "%kernel.project_dir%/src/User/Infrastructure/Controller/Action/*"