services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  user_factories:
    namespace: App\User\Infrastructure\Factory\
    resource: "%kernel.project_dir%/src/User/Infrastructure/Factory/*"

  user_view_factories:
    namespace: App\User\Infrastructure\ReadModel\Factory\
    resource: "%kernel.project_dir%/src/User/Infrastructure/ReadModel/Factory/*"