services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  factories:
    namespace: App\User\Infrastructure\Factory\
    resource: "%kernel.project_dir%/src/User/Infrastructure/Factory/*"

  view_factories:
    namespace: App\User\Infrastructure\View\Factory\
    resource: "%kernel.project_dir%/src/User/Infrastructure/View/Factory/*"