services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  factories:
    namespace: App\User\Infrastructure\Service\Factory\
    resource: "%kernel.project_dir%/src/User/Infrastructure/Service/Factory/*"