services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  user_repositories:
    namespace: App\User\Infrastructure\Repository\
    resource: "%kernel.project_dir%/src/User/Infrastructure/Repository/*"

  user_view_repositories:
    namespace: App\User\Infrastructure\ReadModel\Repository\
    resource: "%kernel.project_dir%/src/User/Infrastructure/ReadModel/Repository/*"