services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  arguments_resolvers:
    namespace: App\Common\Infrastructure\Controller\ArgumentResolver\
    resource: "%kernel.project_dir%/src/Common/Infrastructure/Controller/ArgumentResolver/*"
    tags:
      - { name: 'controller.argument_value_resolver', priority: 50 }