services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  event_stores:
    namespace: App\Common\Infrastructure\EventStore\
    resource: "%kernel.project_dir%/src/Common/Infrastructure/EventStore/*"