services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  event_subscribers:
    namespace: App\Common\Infrastructure\EventSubscriber\
    resource: "%kernel.project_dir%/src/Common/Infrastructure/EventSubscriber/*"
