services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  generators:
    namespace: App\Common\Infrastructure\Generator\
    resource: "%kernel.project_dir%/src/Common/Infrastructure/Generator/*"